### ISSUE TITLE
Two GET requests

### ISSUE THREAD

**Issue by giles247** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#1]
Is it intentional that any column sort or search makes two back end requests?

**Comment by jamesdordoyneon** [comment]
This was not intentional, thank you for bringing this to my attention. I will get a new release created over the weekend to correct this.

**Comment by jamesdordoy** [comment]
Should be fixed now in 1.0.25 update for the vue component. Please 'npm update' and 'npm run dev' to see the changes. Thanks for creating the issue!! :)
