### ISSUE TITLE
500 Error when multiple calls are made.

### ISSUE THREAD

**Issue by EspetoRx** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#17]
Hi I got an 500 error when multiple calls are made to the BackEnd. Can we enable search after some amount of keys pressed?

**Comment by jamesdordoy** [comment]
Hi @EspetoRx,

You should handle this on the frontend. See [here](https://jamesdordoy.github.io/laravel-vue-datatable/props/table) and use the `debounce-delay`

**Comment by jamesdordoy** [comment]
Closed due to inactivity
