### ISSUE TITLE
SQL error when running just your default setup

### ISSUE THREAD

**Issue by pimduijst** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#18]
Hi all,

I hope someone can help me out on this. I got the following sql error message:

`SQLSTATE[42000]: Syntax error or access violation: 1055 'somedatabase.permissions.name' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `permissions`.`id`, `permissions`.`name`, `permissions`.`display_name`, `permissions`.`description` from `permissions` where `permissions`.`deleted_at` is null group by `permissions`.`id`) as `aggregate_table`)`

Steps I have done accordingly:

1. I ran `composer require jamesdordoy/laravelvuedatatable`

2. I added `JamesDordoy\LaravelVueDatatable\Providers\LaravelVueDatatableServiceProvider::class,` in `config/app.php`

3. I ran `php artisan vendor:publish --provider="JamesDordoy\LaravelVueDatatable\Providers\LaravelVueDatatableServiceProvider"`

4. My laravel-vue-datatable.php file
`<?php

return [
    'models' => [
        "search_term" => "searchable",
        "order_term" => "orderable",
    ],
    "default_order_by" => "id",
];`

5. In my Permission model:
`use JamesDordoy\LaravelVueDatatable\Traits\LaravelVueDatatableTrait;

/** @mixin \Eloquent */
final class Permission extends LaratrustPermission
{
    use Sortable, SoftDeletes, LaravelVueDatatableTrait;

    protected $dataTableColumns = [
        'id' => [
            'searchable' => false,
        ],
        'name' => [
            'searchable' => true,
        ],
        'display_name' => [
            'searchable' => true,
        ],
        'description' => [
            'searchable' => true,
        ]
    ];`

6. In my PermissionsController

`use App\Http\Controllers\Controller;
use App\Http\Requests\PermissionRequest;
use App\Http\Requests\Search;
use App\Models\Permission;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Illuminate\Http\Request;`

and 

`public function index(Request $request)
    {
        $length = $request->input('length');
        $orderBy = $request->input('column'); //Index
        $orderByDir = $request->input('dir', 'asc');
        $searchValue = $request->input('search');

        $query = Permission::eloquentQuery($orderBy, $orderByDir, $searchValue);
        $data = $query->paginate($length);

        return new DataTableCollectionResource($data);
    }`

resulting in the above error. What am I missing?

**Comment by jamesdordoy** [comment]
Hi @pimduijst,

You may need to turn off strict mode for SQL.

See [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/relationships).

**Comment by jamesdordoy** [comment]
Closed due to inactivity
