### ISSUE TITLE
Add option to specify other_key in belongsTo relationship

### ISSUE THREAD

**Issue by lukasvida** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#19]
Hello, when using belongsTo relationship, Laravel allows to specify `other_key` which is foreign table column used for joins.
`$this->belongsTo('App\User', 'foreign_key', 'other_key');`

I haven't found an option to specify `other_key` in belongsTo relationship, plugin is now selecting related model by its primary key. Can this feature be added?

**Comment by jamesdordoy** [comment]
Hi @lukasvida,

Ill look into this but im not sure what you mean. A PR would be helpful as an example.
