### ISSUE TITLE
Accessor usage

### ISSUE THREAD

**Issue by hcphoon01** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#26]
I've recently discovered this package and found it very useful so far, although I was wondering if there is any way in which I can use an accessor I have defined within my model (such as the one below) in my table?

```
public function getReportableModelAttribute()
{
    $typeArray = preg_split("\\", $this->reportable_type);
    return end($typeArray);
}
```

**Comment by jamesdordoy** [comment]
Hi @hcphoon01,

Ill keep this as an issue but without a re-write of the backend package, i doubt this would be possible with the current implementation.

**Comment by Masiits** [comment]
Add this function to the model:
```
	/**
	 * The accessors to append to the model's array form.
	 *
	 * @var array
	 */
	protected $appends = [
		'reportable_model'
	];

```
