### ISSUE TITLE
Required parameter $orderByDir follows optional parameter $with

### ISSUE THREAD

**Issue by titkalpesh** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#30]
Getting this error when try to call api. Just want to do demo with one model no relation at all.

![image](https://user-images.githubusercontent.com/58501041/103769337-17153580-504a-11eb-8401-dc63e36d6e5d.png)

**Comment by titkalpesh** [comment]
@jamesdordoy any update or suggestions?

**Comment by jamesdordoy** [comment]
Hey @kalpeshtreesha,

Ill look into this at the weekend but could you paste your code from your model and controller as the error mentions a BelongsToMany relationship.

**Comment by MIcQo** [comment]
This is deprecated in PHP 8 (not verified or confirmed)

```php
public function __invoke($declaredRelationship, $relationships, $with = [], $orderByDir)
```
in `JamesDordoy\LaravelVueDatatable\Classes\Relationships\GetBelongsToManyRelationships`

### How to fix:

Here is two options

1) Swap with with orderByDir
2) Add default value to orderByDir

My tests dropping on that too.

```php
public function testIndex()
    {
        $this->json("get", "/api/clients/list", [
            'search' => "",
            "dir" => "asc",
            "column" => "name",
            "length" => 10,
            "draw" => 0,
            "page" => 1,
        ])->assertStatus(200);
    }
```

@jamesdordoy can you fix this?

**Comment by agdeasis** [comment]
any update for this issue?

**Comment by codeperl** [comment]
To give an hint: I extend that class and override the method.
