### ISSUE TITLE
Unable to filter on values of multiple related models

### ISSUE THREAD

**Issue by KacperGoedemiddag** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#31]
Hi,

I think I found a bug :)

In FilterBelongsToRelationships.php on line 32 there is a return statement. This return should be dropped otherwise the current loop will stop on the first iteration (the first relation). This way filters on other relations won't be applied anymore.

Kind regards,

Kacper Kowalski

**Comment by EspetoRx** [comment]
All other Belongs to return working?

**Comment by KacperGoedemiddag** [comment]
Nope, there are more. 1 or 2 I believe which had to be fixed. Also needed another 1 line fix to make it PHP 8 compatible.
