### ISSUE TITLE
Invalid demo link on README.md

### ISSUE THREAD

**Issue by whambulance** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#34]
Fairly simple issue, the link on the this packages readme goes to an invalid demo url:

[https://jamesdordoy.github.io/vue-datatable/](https://jamesdordoy.github.io/vue-datatable/)

On your other package, you have a valid working link however:

[https://jamesdordoy.github.io/laravel-vue-datatable/](https://jamesdordoy.github.io/laravel-vue-datatable/)

The link should just need updating, unless I'm mistaken and the intent is to show two different demos between the versions? In either case the demo site still remains invalid

**Comment by jamesdordoy** [comment]
Ty fixed that 👍
