### ISSUE TITLE
Pass row data to component?

### ISSUE THREAD

**Issue by vs-mark-graham-smith** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#4]
Hi,

I've been unable so far to figure out a solution to this, although it might be because I haven't looked hard into it.

`
{
	label: '',
	name: 'Edit',
	filterable: false,
	component: DataTableAction
}
`

Here I am loading a component in one of the columns of my DataTable, it works just fine, but I need to pass props into the component using the row's data. The data is showing just fine in the table, but I can't figure out how to pass data to it.

Every row will load the component and I need to pass the id of the column to the component, is this possible and how would it be achieved?

**Comment by jamesdordoy** [comment]
Hey,

In your custom dynamic component you are able to accept the `data` prop which corresponds to the row of data in question. This is automatically parsed to your component by default.

Try adding the following to your `DataTableAction` component:
``` js
props: {
    data: {
        type: Object,
        default: () => ({})
    }
},
```

By default, the row's data will be parsed as an object.

Let me know if that solves your issue.

**Comment by vs-mark-graham-smith** [comment]
> Hey,
> 
> In your custom dynamic component you are able to accept the `data` prop which corresponds to the row of data in question. This is automatically parsed to your component by default.
> 
> Try adding the following to your `DataTableAction` component:
> 
> ```js
> props: {
>     data: {
>         type: Object,
>         default: () => ({})
>     }
> },
> ```
> 
> By default, the row's data will be parsed as an object.
> 
> Let me know if that solves your issue.

Thanks for you reply, this does answer my question, but just to follow up. I was hoping you might be able to tell me how I would go about passing additional data into the component, for example if I wanted to pass a string into the component, how would I achieve this?

**Comment by jamesdordoy** [comment]
No worries,

Passing additional data is not possible with the current API. This could be done using Laravel API Resources and adding the value to each row but this isn't ideal.

I'll have a look at adding a new attribute to the columns array to allow for additional data.

**Comment by jamesdordoy** [comment]
I have added a `meta` property to the columns array. This is an Object property so you should be able to pass anything to your custom component.

See update [0.3.1](https://github.com/jamesdordoy/vue-datatable) for further details.

Let me know if this solves your problem.

**Comment by vs-mark-graham-smith** [comment]
> I have added a `meta` property to the columns array. This is an Object property so you should be able to pass anything to your custom component.
> 
> See update [0.3.1](https://github.com/jamesdordoy/vue-datatable) for further details.
> 
> Let me know if this solves your problem.

Hi, that works fantastic for my needs, thanks for your help :)
