### ISSUE TITLE
Call to undefined method App\User::dataTableQuery()

### ISSUE THREAD

**Issue by Dunkstormen** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#5]
I've been trying to use this VUE component, though I keep getting the error in the title when following the instructions on the package.

ServiceProvider has been added aswell as adding "DataTableCollectionResource" to the Controller itself.

Is there something I'm missing out on?

**Comment by jamesdordoy** [comment]
Hey,

I'm guessing you may have missed adding the Trait to the Model.

More information can be found [here](https://github.com/jamesdordoy/Laravel-Vue-Datatables#use-the-trait)

Let me know if this isn't the case.

**Comment by Dunkstormen** [comment]
From what I understood the trait was optional. However I got it working now, might have been me not understanding what you meant.

**Comment by jamesdordoy** [comment]
No you are correct, the trait is optional but you would then need to filter the data yourself and paginate the results for the "DataTableCollectionResource" to use.

Thanks for bringing that to my attention and i'll try to make the README easier to digest.
