### ISSUE TITLE
How can I remove a row from the DataTable from within a component inside of a column?

### ISSUE THREAD

**Issue by vs-mark-graham-smith** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#6]
Hello, I have a component inside of a column in a datatable, I've been attempting to use the click: {} using identical code from the documentation, but I've hit some issues.

I have a button inside the component which has

`@click="click(data)"`
and the components props include
`click: {}`

Here is the column for this component
`
{
	label: 'Action',
	name: '',
	filterable: false,
	component: DataTableAction,
	click: this.deleteRow,
	meta: {
	updateUrl: '/admin/team-members/update/',
}
`

I've noticed that inside of Vue Dev tools I can see the click event being omitted, but the function called deleteRow is not running at all, I was hoping you might be able to tell me where I was going wrong?

**Comment by jamesdordoy** [comment]
Hello,

This is due to the API changing between version 0.2.0 and 0.3.0.

The click event was changed to two new column props:
- event (String) e.g. click, focus etc.
- handler (Function) the event to fire

Apologies, it looks like i forgot to update the README when adding this feature. Hence the confusion.

[View here](https://github.com/jamesdordoy/vue-datatable#dynamic-datatable-columns) for a code example.

I'll adjust the README to reflect this tonight.

**Comment by jamesdordoy** [comment]
Hey,

i've updated the README to reflect the 0.3.1 changes. You can see the README changes here 6630662.

The README has been reduced and has a link to the Vue component repo which is up to date.

After reading your title for the issue above, i wondered if you was trying to remove the row using JavaScript, on the client side? Currently this is not possible with the package as it is driven server-side.

Let me know i can help anymore with the issue.

**Comment by vs-mark-graham-smith** [comment]
> After reading your title for the issue above, i wondered if you was trying to remove the row using JavaScript, on the client side? Currently this is not possible with the package as it is driven server-side.

Hi, I was originally trying to delete a row from the table client-side, currently I have a delete button inside of my action component which I use the @click="click(data)" to pass the row to a method in the data table to send an axios request to delete the row inside of my database.

After this I wanted the data table to update and reflect the change. I couldn't find much on the documentation but I settled with using a vue ref and the line to update the data table.

`
this.$refs.table.getData();
`

is there a better solution for this?

**Comment by jamesdordoy** [comment]
Currently no, the only other option you would have is to manipulate the url as this is watched by the data table and would also refresh the data but that would be less ideal than your solution.

I am open to any suggestions you may have on improving the functionality though.
