### ISSUE TITLE
[question] Work with (very) large table datas ?

### ISSUE THREAD

**Issue by LPABelgium** [jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#9]
Hi,
It's not an issue, just a question.

Does it work well for very large data tables with more than 20.000 rows with ± 30 cells a row ?

**Comment by jamesdordoy** [comment]
Hey,

The table makes use of Laravel's model pagination methods and AJAX so only a subset of data will be loaded at any point e.g. 30 or 100 rows. So you shouldn't have any issue with performance when loading data.

I haven't needed to create a data table before with 30 columns a row, so i'm not able to tell you what the performance would be like for you but i may suggest splitting the table up or not displaying all fields if not required as 30 columns may be difficult to display cleanly.

Hopefully that helps :)

**Comment by LPABelgium** [comment]
Hi @jamesdordoy,
Thanks for your quick answer.
I'll give it a try.
Unfortunately, the 30 cols are required... Table will have a horizontal scroll

**Comment by jamesdordoy** [comment]
No worries, let me know if i can be of anymore help
